run:
  dir: ${training.out_dir}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${training.out_dir}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
